chore: merge fedora changes into submodule (#9)
* - remove old patch that seems to be the cause of a crash
    when the user set user.max_user_namespaces to 0

* - fix rhbz#2294773 - Allow enabling vulkan on ozone wayland for AMD vaapi
- add ppc64le patch to fix runtime assertion trap on ppc64el systems
- refresh ppc64le patch to work around broken 64k allocator code on arm64

* - update to 127.0.6533.99
  * Critical CVE-2024-7532: Out of bounds memory access in ANGLE
  * High CVE-2024-7533: Use after free in Sharing
  * High CVE-2024-7550: Type Confusion in V8
  * High CVE-2024-7534: Heap buffer overflow in Layout
  * High CVE-2024-7535: Inappropriate implementation in V8
  * High CVE-2024-7536: Use after free in WebAudio

* update to 128.0.6613.119

* - fix build error and disable build warnings on ppc64le
- drop obsolete patches

* workaround for build error on epel and fedora39

* removed patch for 64kpage support on aarch64, merged by upstream

* enable bundlelibopenjpeg2 as workaround for old openjpeg on epel

  error: use of undeclared identifier 'opj_decoder_set_strict_mode'

* - removed workaround for missing bindgen-cli on el8
- removed partition-alloc-4k-detect.patch

* - update to 128.0.6613.137
  * High CVE-2024-8636: Heap buffer overflow in Skia
  * High CVE-2024-8637: Use after free in Media Router
  * High CVE-2024-8638: Type Confusion in V8
  * High CVE-2024-8639: Use after free in Autofill

* set correct rust_bindgen_root for el8

* - update to 129.0.6668.58
  * High CVE-2024-8904: Type Confusion in V8
  * Medium CVE-2024-8905: Inappropriate implementation in V8
  * Medium CVE-2024-8906: Incorrect security UI in Downloads
  * Medium CVE-2024-8907: Insufficient data validation in Omnibox
  * Low CVE-2024-8908: Inappropriate implementation in Autofill
  * Low CVE-2024-8909: Inappropriate implementation in UI

* fix: remove unused patch

---------

Co-authored-by: Than Ngo <than@redhat.com>